#!/bin/bash 
git rm --cached ./main.o
git rm --cached ./chibios/os/kernel/src/chmtx.o
git rm --cached ./chibios/os/kernel/src/chdynamic.o
git rm --cached ./chibios/os/kernel/src/chdebug.o
git rm --cached ./chibios/os/kernel/src/chqueues.o
git rm --cached ./chibios/os/kernel/src/chmemcore.o
git rm --cached ./chibios/os/kernel/src/chmempools.o
git rm --cached ./chibios/os/kernel/src/chthreads.o
git rm --cached ./chibios/os/kernel/src/chevents.o
git rm --cached ./chibios/os/kernel/src/chsem.o
git rm --cached ./chibios/os/kernel/src/chschd.o
git rm --cached ./chibios/os/kernel/src/chcond.o
git rm --cached ./chibios/os/kernel/src/chmboxes.o
git rm --cached ./chibios/os/kernel/src/chregistry.o
git rm --cached ./chibios/os/kernel/src/chmsg.o
git rm --cached ./chibios/os/kernel/src/chheap.o
git rm --cached ./chibios/os/kernel/src/chlists.o
git rm --cached ./chibios/os/kernel/src/chsys.o
git rm --cached ./chibios/os/kernel/src/chvt.o
git rm --cached ./chibios/os/various/syscalls.o
git rm --cached ./chibios/os/various/evtimer.o
git rm --cached ./chibios/os/ports/GCC/ARMCMx/crt0_v7m.o
git rm --cached ./chibios/os/ports/GCC/ARMCMx/STM32/vectors.o
git rm --cached ./chibios/os/ports/GCC/ARMCMx/nvic.o
git rm --cached ./chibios/os/ports/GCC/ARMCMx/chcore_v7m.o
git rm --cached ./chibios/os/ports/GCC/ARMCMx/chcore.o
git rm --cached ./chibios/os/hal/platforms/STM32/uart_lld.o
git rm --cached ./chibios/os/hal/platforms/STM32/stm32_dma.o
git rm --cached ./chibios/os/hal/platforms/STM32/serial_lld.o
git rm --cached ./chibios/os/hal/platforms/STM32/can_lld.o
git rm --cached ./chibios/os/hal/platforms/STM32/pwm_lld.o
git rm --cached ./chibios/os/hal/platforms/STM32/adc_lld.o
git rm --cached ./chibios/os/hal/platforms/STM32/pal_lld.o
git rm --cached ./chibios/os/hal/platforms/STM32/spi_lld.o
git rm --cached ./chibios/os/hal/platforms/STM32/hal_lld.o
git rm --cached ./chibios/os/hal/src/pwm.o
git rm --cached ./chibios/os/hal/src/mmc_spi.o
git rm --cached ./chibios/os/hal/src/can.o
git rm --cached ./chibios/os/hal/src/pal.o
git rm --cached ./chibios/os/hal/src/adc.o
git rm --cached ./chibios/os/hal/src/spi.o
git rm --cached ./chibios/os/hal/src/hal.o
git rm --cached ./chibios/os/hal/src/uart.o
git rm --cached ./chibios/os/hal/src/mac.o
git rm --cached ./chibios/os/hal/src/serial.o
git rm --cached ./chibios/board/board.o
git rm --cached ./flight_controller.bin
git rm --cached ./flight_controller.hex
git rm --cached ./flight_controller.elf
git rm --cached ./flight_controller.dmp
git rm --cached ./chibios/os/kernel/src/chmempools.lst
git rm --cached ./chibios/os/kernel/src/chmtx.lst
git rm --cached ./chibios/os/kernel/src/chlists.lst
git rm --cached ./chibios/os/kernel/src/chregistry.lst
git rm --cached ./chibios/os/kernel/src/chmboxes.lst
git rm --cached ./chibios/os/kernel/src/chevents.lst
git rm --cached ./chibios/os/kernel/src/chmsg.lst
git rm --cached ./chibios/os/kernel/src/chthreads.lst
git rm --cached ./chibios/os/kernel/src/chsem.lst
git rm --cached ./chibios/os/kernel/src/chsys.lst
git rm --cached ./chibios/os/kernel/src/chvt.lst
git rm --cached ./chibios/os/kernel/src/chschd.lst
git rm --cached ./chibios/os/kernel/src/chheap.lst
git rm --cached ./chibios/os/kernel/src/chdebug.lst
git rm --cached ./chibios/os/kernel/src/chdynamic.lst
git rm --cached ./chibios/os/kernel/src/chmemcore.lst
git rm --cached ./chibios/os/kernel/src/chqueues.lst
git rm --cached ./chibios/os/kernel/src/chcond.lst
git rm --cached ./chibios/os/various/syscalls.lst
git rm --cached ./chibios/os/various/evtimer.lst
git rm --cached ./chibios/os/ports/GCC/ARMCMx/nvic.lst
git rm --cached ./chibios/os/ports/GCC/ARMCMx/STM32/vectors.lst
git rm --cached ./chibios/os/ports/GCC/ARMCMx/chcore.lst
git rm --cached ./chibios/os/ports/GCC/ARMCMx/crt0_v7m.lst
git rm --cached ./chibios/os/ports/GCC/ARMCMx/chcore_v7m.lst
git rm --cached ./chibios/os/hal/platforms/STM32/spi_lld.lst
git rm --cached ./chibios/os/hal/platforms/STM32/pal_lld.lst
git rm --cached ./chibios/os/hal/platforms/STM32/hal_lld.lst
git rm --cached ./chibios/os/hal/platforms/STM32/stm32_dma.lst
git rm --cached ./chibios/os/hal/platforms/STM32/can_lld.lst
git rm --cached ./chibios/os/hal/platforms/STM32/pwm_lld.lst
git rm --cached ./chibios/os/hal/platforms/STM32/adc_lld.lst
git rm --cached ./chibios/os/hal/platforms/STM32/serial_lld.lst
git rm --cached ./chibios/os/hal/platforms/STM32/uart_lld.lst
git rm --cached ./chibios/os/hal/src/pal.lst
git rm --cached ./chibios/os/hal/src/hal.lst
git rm --cached ./chibios/os/hal/src/can.lst
git rm --cached ./chibios/os/hal/src/spi.lst
git rm --cached ./chibios/os/hal/src/mac.lst
git rm --cached ./chibios/os/hal/src/uart.lst
git rm --cached ./chibios/os/hal/src/adc.lst
git rm --cached ./chibios/os/hal/src/serial.lst
git rm --cached ./chibios/os/hal/src/mmc_spi.lst
git rm --cached ./chibios/os/hal/src/pwm.lst
git rm --cached ./chibios/board/board.lst
git rm --cached ./main.lst
git rm --cached ./flight_controller.map
